#!/usr/bin/env bash
# Xbox Smart DNS + Telegram manager bot - one-line installer (Ubuntu/Debian).
#
#   bash <(curl -fsSL https://raw.githubusercontent.com/YOUR_USER/YOUR_REPO/main/install.sh)
#
# Optional: BOT_TOKEN=123:abc bash <(curl -fsSL ...)   (skips the token question)
# Safe to re-run: it updates the scripts and restarts the bot without losing users.
set -euo pipefail

[ "$(id -u)" -eq 0 ] || { echo "Run as root first:  sudo -i   (then paste the command again)"; exit 1; }
command -v apt-get >/dev/null || { echo "This installer supports Ubuntu/Debian only."; exit 1; }
export DEBIAN_FRONTEND=noninteractive

need=""
command -v curl >/dev/null || need="$need curl"
command -v python3 >/dev/null || need="$need python3"
if [ -n "$need" ]; then apt-get update -qq; apt-get install -y -qq $need; fi

# ---- 1. Telegram bot token (checked before anything is changed) ----
BOT_TOKEN="${BOT_TOKEN:-}"
if [ -z "$BOT_TOKEN" ]; then
  echo "1) In Telegram open @BotFather, send /newbot, and copy the token it gives you."
  read -r -p "2) Paste the bot token here: " BOT_TOKEN </dev/tty
fi
BOT_TOKEN=$(printf '%s' "$BOT_TOKEN" | tr -d '[:space:]')
[[ $BOT_TOKEN =~ ^[0-9]+:[A-Za-z0-9_-]{30,}$ ]] || { echo "That does not look like a bot token."; exit 1; }
ME=$(curl -fsS --max-time 20 "https://api.telegram.org/bot$BOT_TOKEN/getMe") \
  || { echo "Telegram rejected the token (or api.telegram.org is unreachable from this server)."; exit 1; }
BOT_USER=$(printf '%s' "$ME" | python3 -c 'import sys,json; print(json.load(sys.stdin)["result"]["username"])')

# ---- 2. Unpack the components ----
T=$(mktemp -d)
trap 'rm -rf "$T"' EXIT

cat > "$T/smartdns.sh" <<'SMARTDNS_SH_PAYLOAD_EOF'
#!/usr/bin/env bash
# smartdns - personal Xbox Smart DNS (dnsmasq + sniproxy) for a VPS that already runs Amnezia VPN.
#
#   sudo bash smartdns.sh install [HOME_IP ...]      one-time setup (IPs optional)
#   sudo smartdns ip <IP> [more IPs] | none          set the allowed IP list (replaces the old list)
#   sudo smartdns add <domain>                       route one more domain through the VPS
#   sudo smartdns remove <domain>
#   smartdns list | status | logs
#   sudo smartdns uninstall                          remove everything
#
# Safety: it never touches Docker/Amnezia. If port 53, 80 or 443 is already in use, it stops
# before changing anything. Only your home IP is allowed to use the service.

set -euo pipefail

CONF_DIR=/etc/smartdns
DOMAINS_FILE="$CONF_DIR/domains.txt"
STATE_FILE="$CONF_DIR/state.env"
SNI_CONF="$CONF_DIR/sniproxy.conf"
DNSMASQ_CONF=/etc/dnsmasq.d/smartdns.conf
FW_SCRIPT=/usr/local/sbin/smartdns-firewall.sh
BIN=/usr/local/bin/smartdns
UNIT_SNI=/etc/systemd/system/smartdns-sniproxy.service
UNIT_FW=/etc/systemd/system/smartdns-firewall.service
CHAIN=SMARTDNS

say() { printf '%s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
need_root() { [ "$(id -u)" -eq 0 ] || die "Run this with sudo (or as root)."; }

valid_ip() {
  local ip=$1 o
  local -a parts
  [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || return 1
  IFS=. read -ra parts <<<"$ip"
  for o in "${parts[@]}"; do (( 10#$o <= 255 )) || return 1; done
  return 0
}

valid_domain() { [[ $1 =~ ^[a-z0-9]([a-z0-9.-]*[a-z0-9])?\.[a-z]{2,}$ ]]; }

# true if something (other than loopback-only services) listens on proto(t|u) port
port_busy() {
  local out
  out=$(ss -H -ln"$1" "sport = :$2" 2>/dev/null | awk '{print $4}' | grep -Ev '^(127\.|\[::1\])' || true)
  [ -n "$out" ]
}

pkg_installed() { dpkg-query -W -f='${Status}' "$1" 2>/dev/null | grep -q 'install ok installed'; }

detect_ips() {
  LOCAL_IP=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<NF;i++) if($i=="src"){print $(i+1); exit}}')
  [ -n "${LOCAL_IP:-}" ] || die "Could not detect this server's IP address."
  PUBLIC_IP=$(curl -4 -fsS --max-time 10 https://api.ipify.org 2>/dev/null \
    || curl -4 -fsS --max-time 10 https://ifconfig.me 2>/dev/null || true)
  valid_ip "${PUBLIC_IP:-x}" || PUBLIC_IP=$LOCAL_IP
}

render_configs() {
  # shellcheck disable=SC1090
  . "$STATE_FILE"
  local d re
  local -a DOMS
  mapfile -t DOMS < <(grep -Ev '^[[:space:]]*(#|$)' "$DOMAINS_FILE" || true)

  {
    echo "# Generated by smartdns. Use 'smartdns add/remove' instead of editing."
    echo "listen-address=$LOCAL_IP"
    echo "bind-dynamic"
    echo "no-resolv"
    echo "no-hosts"
    echo "cache-size=1000"
    echo "log-queries"
    echo "server=1.1.1.1"
    echo "server=9.9.9.9"
    for d in "${DOMS[@]}"; do echo "address=/$d/$PUBLIC_IP"; done
  } > "$DNSMASQ_CONF"

  {
    cat <<EOF
user daemon
pidfile /run/smartdns-sniproxy.pid

error_log {
    syslog daemon
    priority notice
}

# IMPORTANT: sniproxy must use real DNS servers, never this server's own dnsmasq (that would loop).
resolver {
    nameserver 1.1.1.1
    nameserver 9.9.9.9
    mode ipv4_only
}

listener $LOCAL_IP:80 {
    proto http
    table smart_http
}

listener $LOCAL_IP:443 {
    proto tls
    table smart_tls
}

table smart_http {
EOF
    for d in "${DOMS[@]}"; do re=${d//./\\.}; echo "    (^|\\.)$re\$ *:80"; done
    echo "}"
    echo
    echo "table smart_tls {"
    for d in "${DOMS[@]}"; do re=${d//./\\.}; echo "    (^|\\.)$re\$ *:443"; done
    echo "}"
  } > "$SNI_CONF"
}

restart_services() {
  systemctl restart dnsmasq
  systemctl restart smartdns-sniproxy
}

do_uninstall() {
  set +e
  systemctl disable --now smartdns-bot 2>/dev/null
  rm -f /etc/systemd/system/smartdns-bot.service
  rm -rf /opt/smartdns-bot
  systemctl disable --now smartdns-sniproxy 2>/dev/null
  systemctl disable --now smartdns-firewall 2>/dev/null
  systemctl disable --now dnsmasq 2>/dev/null
  if command -v iptables >/dev/null 2>&1; then
    # shellcheck disable=SC2086
    iptables -S INPUT 2>/dev/null | grep -- "-j $CHAIN" | sed 's/^-A/-D/' | while read -r r; do iptables $r; done
    iptables -F "$CHAIN" 2>/dev/null
    iptables -X "$CHAIN" 2>/dev/null
  fi
  rm -f "$UNIT_SNI" "$UNIT_FW" "$DNSMASQ_CONF" "$FW_SCRIPT"
  rm -rf "$CONF_DIR"
  systemctl daemon-reload 2>/dev/null
  DEBIAN_FRONTEND=noninteractive apt-get purge -y -qq sniproxy dnsmasq >/dev/null 2>&1
  [ "${MADE_PRC:-0}" = 1 ] && rm -f /usr/sbin/policy-rc.d
  rm -f "$BIN"
}

cmd_install() {
  need_root
  [ ! -f "$STATE_FILE" ] || die "Already installed. Use 'sudo smartdns ip <new IP>' or 'sudo smartdns uninstall'."
  [ -f "${BASH_SOURCE[0]}" ] || die "Save this script to a file first, then run it (do not pipe it into bash)."
  command -v apt-get >/dev/null || die "This script supports Ubuntu/Debian only."
  local ip
  for ip in "$@"; do valid_ip "$ip" || die "'$ip' is not a valid IPv4 address."; done

  # ---- Safety checks: nothing has been changed yet ----
  if pkg_installed sniproxy || pkg_installed dnsmasq; then
    die "sniproxy or dnsmasq is already installed on this server. Not touching it. Nothing was changed."
  fi
  local spec busy=0
  for spec in "u 53" "t 53" "t 80" "t 443"; do
    if port_busy "${spec% *}" "${spec#* }"; then
      say "Port ${spec#* } ($([ "${spec% *}" = t ] && echo TCP || echo UDP)) is already used by another program on this server."
      busy=1
    fi
  done
  if [ "$busy" = 1 ]; then
    say "Most likely Amnezia (e.g. Xray/OpenVPN on 443). To see who: sudo ss -lntup | grep -E ':(53|80|443)\\b'"
    say "Nothing was changed. Fix: change that Amnezia protocol's port in the Amnezia app, or use a server/IP where these ports are free."
    exit 1
  fi

  # ---- Install (with automatic rollback if anything fails) ----
  CHANGED=1
  DONE=0
  trap 'if [ "${DONE:-0}" != 1 ]; then echo "Install failed - rolling back..." >&2; do_uninstall; fi' EXIT

  local prc=/usr/sbin/policy-rc.d
  MADE_PRC=0
  if [ ! -e "$prc" ]; then printf '#!/bin/sh\nexit 101\n' > "$prc"; chmod +x "$prc"; MADE_PRC=1; fi
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y -qq sniproxy dnsmasq iptables curl
  [ "$MADE_PRC" = 1 ] && rm -f "$prc"

  systemctl disable --now sniproxy >/dev/null 2>&1 || true
  if [ -f /etc/default/dnsmasq ] && ! grep -q '^IGNORE_RESOLVCONF=yes' /etc/default/dnsmasq; then
    echo 'IGNORE_RESOLVCONF=yes' >> /etc/default/dnsmasq
  fi

  detect_ips
  mkdir -p "$CONF_DIR"
  cat > "$DOMAINS_FILE" <<'EOF'
# One domain per line (subdomains are included automatically).
xboxlive.com
xbox.com
xboxservices.com
gamepass.com
live.com
microsoft.com
microsoftonline.com
msauth.net
msftauth.net
msftconnecttest.com
EOF
  cat > "$STATE_FILE" <<EOF
LOCAL_IP=$LOCAL_IP
PUBLIC_IP=$PUBLIC_IP
HOME_IPS="$*"
EOF
  chmod 600 "$STATE_FILE"
  cp -f "${BASH_SOURCE[0]}" "$BIN" && chmod +x "$BIN"

  # Firewall: only whitelisted home IPs may reach DNS/HTTP/HTTPS on this server's address.
  # Only these three ports are touched; Docker/Amnezia rules are left alone.
  cat > "$FW_SCRIPT" <<'EOF'
#!/bin/sh
. /etc/smartdns/state.env
CHAIN=SMARTDNS
iptables -N $CHAIN 2>/dev/null || true
iptables -F $CHAIN
for ip in $HOME_IPS; do iptables -A $CHAIN -s "$ip" -j RETURN; done
iptables -A $CHAIN -j DROP
for spec in "udp 53" "tcp 53" "tcp 80" "tcp 443"; do
  set -- $spec
  iptables -C INPUT -d "$LOCAL_IP" -p "$1" --dport "$2" -j $CHAIN 2>/dev/null || \
    iptables -I INPUT 1 -d "$LOCAL_IP" -p "$1" --dport "$2" -j $CHAIN
done
EOF
  chmod +x "$FW_SCRIPT"

  local sniproxy_bin
  sniproxy_bin=$(command -v sniproxy) || die "sniproxy binary not found."

  cat > "$UNIT_FW" <<EOF
[Unit]
Description=Smart DNS firewall (only whitelisted home IPs)
After=network-online.target
Wants=network-online.target
Before=dnsmasq.service smartdns-sniproxy.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=$FW_SCRIPT

[Install]
WantedBy=multi-user.target
EOF

  cat > "$UNIT_SNI" <<EOF
[Unit]
Description=Smart DNS SNI proxy (personal)
After=network-online.target smartdns-firewall.service
Wants=network-online.target smartdns-firewall.service

[Service]
Type=forking
PIDFile=/run/smartdns-sniproxy.pid
ExecStart=$sniproxy_bin -c $SNI_CONF
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

  render_configs
  dnsmasq --test -C "$DNSMASQ_CONF" >/dev/null 2>&1 || die "dnsmasq config check failed."

  systemctl daemon-reload
  systemctl enable --now smartdns-firewall
  systemctl enable dnsmasq >/dev/null 2>&1
  systemctl enable smartdns-sniproxy >/dev/null 2>&1
  restart_services
  sleep 2
  systemctl is-active --quiet dnsmasq || die "dnsmasq did not start (see: journalctl -u dnsmasq -n 30)."
  systemctl is-active --quiet smartdns-sniproxy || die "sniproxy did not start (see: journalctl -u smartdns-sniproxy -n 30)."

  DONE=1
  trap - EXIT
  say
  say "Done. Smart DNS is running."
  say "  On your Xbox set DNS to (manual):  $PUBLIC_IP"
  say "  Secondary DNS: same IP, or 1.1.1.1"
  say "  Allowed home IP(s): ${*:-none yet}"
  say "To change the allowed IP later:  sudo smartdns ip <NEW_IP>"
  say "Also make sure your VPS provider's own firewall (if any) allows ports 53 (UDP+TCP), 80 and 443."
}

cmd_ip() {
  need_root
  [ -f "$STATE_FILE" ] || die "Not installed."
  [ $# -ge 1 ] || die "Usage: sudo smartdns ip <YOUR_HOME_IP> [more IPs]   (or: none)"
  local ip
  if [ "$1" = none ]; then
    set --
  else
    for ip in "$@"; do valid_ip "$ip" || die "'$ip' is not a valid IPv4 address."; done
  fi
  sed -i "s/^HOME_IPS=.*/HOME_IPS=\"$*\"/" "$STATE_FILE"
  "$FW_SCRIPT"
  say "Allowed IP(s) now: ${*:-none}"
}

cmd_add() {
  need_root
  [ -f "$STATE_FILE" ] || die "Not installed."
  local d=${1:-}
  d=${d,,}
  valid_domain "$d" || die "Usage: sudo smartdns add example.com"
  grep -qx "$d" "$DOMAINS_FILE" && { say "$d is already in the list."; return 0; }
  echo "$d" >> "$DOMAINS_FILE"
  render_configs
  restart_services
  say "Added $d (subdomains included)."
}

cmd_remove() {
  need_root
  [ -f "$STATE_FILE" ] || die "Not installed."
  local d=${1:-}
  d=${d,,}
  valid_domain "$d" || die "Usage: sudo smartdns remove example.com"
  grep -vx "$d" "$DOMAINS_FILE" > "$DOMAINS_FILE.new" || true
  mv "$DOMAINS_FILE.new" "$DOMAINS_FILE"
  render_configs
  restart_services
  say "Removed $d."
}

cmd_list() {
  [ -f "$DOMAINS_FILE" ] || die "Not installed."
  grep -Ev '^[[:space:]]*(#|$)' "$DOMAINS_FILE" || true
}

cmd_status() {
  [ -f "$STATE_FILE" ] || die "Not installed."
  # shellcheck disable=SC1090
  . "$STATE_FILE"
  say "Set this DNS on your Xbox: $PUBLIC_IP"
  say "Allowed home IP(s):        $HOME_IPS"
  say "dnsmasq (DNS):             $(systemctl is-active dnsmasq || true)"
  say "sniproxy (proxy):          $(systemctl is-active smartdns-sniproxy || true)"
  say "Domains routed:            $(cmd_list | wc -l)"
}

cmd_logs() {
  say "Domains asked in the last 30 minutes (count, domain):"
  journalctl -u dnsmasq --since "30 min ago" -o cat --no-pager 2>/dev/null \
    | awk '$1 ~ /^query\[(A|AAAA)\]$/ {print $2}' | sort | uniq -c | sort -rn | head -40 || true
}

cmd_uninstall() {
  need_root
  say "Removing Smart DNS (Amnezia is not touched)..."
  do_uninstall
  say "Done."
}

usage() {
  cat <<EOF
Usage:
  sudo bash smartdns.sh install [HOME_IP ...]
  sudo smartdns ip <IP> [more IPs] | none
  sudo smartdns add <domain>      /  sudo smartdns remove <domain>
  smartdns list | status | logs
  sudo smartdns uninstall
EOF
}

main() {
  case "${1:-}" in
    install)   shift; cmd_install "$@" ;;
    ip)        shift; cmd_ip "$@" ;;
    add)       shift; cmd_add "$@" ;;
    remove)    shift; cmd_remove "$@" ;;
    list)      cmd_list ;;
    status)    cmd_status ;;
    logs)      cmd_logs ;;
    uninstall) cmd_uninstall ;;
    *)         usage ;;
  esac
}

main "$@"
exit 0
SMARTDNS_SH_PAYLOAD_EOF

cat > "$T/bot.py" <<'BOT_PY_PAYLOAD_EOF'
#!/usr/bin/env python3
"""Smart DNS manager bot (Telegram, stdlib only).

Authorised Telegram users register their home IP so the smart DNS accepts them.
Two ways to register: send the IP to the bot, or open a personal link from the
home network (the server sees the IP itself). Roles: owner > admin > user.
"""
import ipaddress
import json
import os
import re
import secrets
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

CONF_PATH = os.environ.get("SMARTDNS_BOT_CONF", "/etc/smartdns/bot.json")
DATA_PATH = os.environ.get("SMARTDNS_BOT_DATA", "/etc/smartdns/users.json")
SMARTDNS = os.environ.get("SMARTDNS_BIN", "/usr/local/bin/smartdns")
MAX_IPS_PER_USER = 3
INVITE_TTL = 24 * 3600

LOCK = threading.RLock()
with open(CONF_PATH) as _f:
    CONF = json.load(_f)
TOKEN = CONF["token"]
SERVER_IP = CONF["server_ip"]
LINK_PORT = int(CONF["link_port"])
BOT_USERNAME = ""


def log(*a):
    print(*a, flush=True)


def eq(a, b):
    return secrets.compare_digest(str(a).encode(), str(b).encode())


# ---------------------------------------------------------------- storage
def load():
    try:
        with open(DATA_PATH) as f:
            s = json.load(f)
    except FileNotFoundError:
        s = {}
    s.setdefault("owner_claim", None)
    s.setdefault("users", {})
    s.setdefault("invites", {})
    return s


STATE = load()


def save():
    tmp = DATA_PATH + ".tmp"
    with open(tmp, "w") as f:
        json.dump(STATE, f, indent=1)
    os.chmod(tmp, 0o600)
    os.replace(tmp, DATA_PATH)


# ---------------------------------------------------------------- telegram
def tg(method, **params):
    req = urllib.request.Request(
        f"https://api.telegram.org/bot{TOKEN}/{method}",
        data=json.dumps(params).encode(),
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=70) as r:
        return json.load(r)


def send(chat_id, text, kb=None):
    p = {
        "chat_id": chat_id,
        "text": text[:4000],
        "link_preview_options": {"is_disabled": True},
    }
    if kb is not None:
        p["reply_markup"] = {"keyboard": kb, "resize_keyboard": True}
    try:
        tg("sendMessage", **p)
    except Exception as e:  # noqa: BLE001
        log("send failed:", repr(e))


# ---------------------------------------------------------------- logic
def role(uid):
    u = STATE["users"].get(uid)
    return u["role"] if u else None


def is_admin(uid):
    return role(uid) in ("owner", "admin")


def new_user(uid, name, r):
    STATE["users"][uid] = {
        "name": name,
        "role": r,
        "token": secrets.token_urlsafe(24),
        "ips": [],
    }


def parse_ip(s):
    try:
        ip = ipaddress.IPv4Address(s.strip())
    except ValueError:
        return None
    if not ip.is_global or str(ip) == SERVER_IP:
        return None
    return str(ip)


def all_ips():
    return sorted({e["ip"] for u in STATE["users"].values() for e in u["ips"]})


def cli(*args):
    r = subprocess.run([SMARTDNS, *args], capture_output=True, text=True, timeout=90)
    return ((r.stdout or "") + (r.stderr or "")).strip() or "(no output)", r.returncode


def apply_ips():
    out, code = cli("ip", *(all_ips() or ["none"]))
    if code != 0:
        raise RuntimeError(out[:300])


def set_ip(uid, ip):
    with LOCK:
        u = STATE["users"][uid]
        u["ips"] = [e for e in u["ips"] if e["ip"] != ip]
        u["ips"].insert(0, {"ip": ip, "ts": int(time.time())})
        del u["ips"][MAX_IPS_PER_USER:]
        save()
        apply_ips()


def ago(ts):
    d = int(time.time()) - int(ts)
    if d < 90:
        return "همین الان"
    if d < 5400:
        return f"{d // 60} دقیقه پیش"
    if d < 172800:
        return f"{d // 3600} ساعت پیش"
    return f"{d // 86400} روز پیش"


ROLE_ICON = {"owner": "👑", "admin": "🛡", "user": "👤"}

BUTTONS = {
    "🔗 لینک ثبت IP": "/link",
    "📍 IP من": "/myip",
    "ℹ️ راهنما": "/help",
    "👥 کاربران": "/users",
    "➕ دعوت کاربر": "/invite",
    "📊 وضعیت": "/status",
}

HELP_USER = (
    "🔗 لینک ثبت IP — لینک شخصی تو. با گوشی یا کامپیوتری که به اینترنت خانه‌ی ایکس‌باکس وصل است "
    "(VPN خاموش) بازش کن تا IP همان‌جا ثبت شود.\n"
    "📍 IP من — IPهای ثبت‌شده‌ی تو.\n"
    "یا خود IP را برای ربات بفرست (مثلاً 5.120.10.20).\n"
    "هر نفر حداکثر ۳ IP آخرش نگه داشته می‌شود."
)
HELP_ADMIN = (
    "\n\nدستورهای مدیر:\n"
    "/users — لیست کاربران و IPها\n"
    "/invite — دعوت کاربر (لینک یک‌بار مصرف، ۲۴ ساعت)\n"
    "/remove ID — حذف کاربر\n"
    "/setip ID IP — ثبت IP برای یک کاربر\n"
    "/delip IP — حذف یک IP از همه\n"
    "/status — وضعیت سرویس\n"
    "/domains — دامنه‌ها | /adddomain d | /removedomain d\n"
    "/logs — دامنه‌هایی که کنسول اخیراً پرسیده"
)
HELP_OWNER = (
    "\n\nمخصوص مالک:\n"
    "/invite admin — دعوت ادمین\n"
    "/promote ID | /demote ID — ارتقا/تنزل"
)


def keyboard(uid):
    rows = [["🔗 لینک ثبت IP", "📍 IP من"], ["ℹ️ راهنما"]]
    if is_admin(uid):
        rows.append(["👥 کاربران", "➕ دعوت کاربر", "📊 وضعیت"])
    return rows


def help_text(uid):
    t = HELP_USER
    if is_admin(uid):
        t += HELP_ADMIN
    if role(uid) == "owner":
        t += HELP_OWNER
    return t


def my_ips_text(uid):
    ips = STATE["users"][uid]["ips"]
    if not ips:
        return "هنوز IP‌ای ثبت نکردی. /link را بزن یا IP را بفرست."
    return "IPهای ثبت‌شده:\n" + "\n".join(f"• {e['ip']} ({ago(e['ts'])})" for e in ips)


def redeem(uid, name, code, cid):
    """Handle /start <code>. Returns True if the message was fully handled."""
    now = time.time()
    for c in [c for c, v in STATE["invites"].items() if v["expires"] < now]:
        del STATE["invites"][c]
    claim = STATE.get("owner_claim")
    if claim and eq(code, claim):
        STATE["owner_claim"] = None
        new_user(uid, name, "owner")
        save()
        send(cid, "✅ تو مالک ربات شدی.\n\n" + help_text(uid), keyboard(uid))
        return True
    for c, v in list(STATE["invites"].items()):
        if eq(code, c):
            if uid in STATE["users"]:
                send(cid, "تو قبلاً عضو هستی.", keyboard(uid))
                return True
            del STATE["invites"][c]
            new_user(uid, name, v["role"])
            save()
            send(cid, "✅ دسترسی‌ات فعال شد.\n\n" + help_text(uid), keyboard(uid))
            if v.get("by"):
                send(int(v["by"]), f"✅ {name} با دعوت تو وارد شد ({v['role']}).")
            return True
    return False


def target_id(arg):
    a = arg.split()[0] if arg.split() else ""
    return a if a in STATE["users"] else None


def handle(msg):
    chat = msg["chat"]
    if chat.get("type") != "private":
        return
    cid = chat["id"]
    frm = msg["from"]
    uid = str(frm["id"])
    name = (
        " ".join(x for x in [frm.get("first_name"), frm.get("last_name")] if x)
        or frm.get("username")
        or uid
    )
    text = (msg.get("text") or "").strip()
    text = BUTTONS.get(text, text)
    cmd, _, arg = text.partition(" ")
    cmd = cmd.split("@")[0].lower()
    arg = arg.strip()

    with LOCK:
        if cmd == "/start" and arg and redeem(uid, name, arg, cid):
            return
        if uid not in STATE["users"]:
            send(cid, "⛔ دسترسی نداری. از مدیر ربات لینک دعوت بگیر.")
            return
        me = STATE["users"][uid]
        admin = is_admin(uid)
        owner = role(uid) == "owner"

        # a bare IPv4 address = register it
        if cmd == "/ip" or re.fullmatch(r"\d{1,3}(\.\d{1,3}){3}", text):
            raw = arg if cmd == "/ip" else text
            ip = parse_ip(raw)
            if not ip:
                send(cid, "IP معتبر نیست (باید یک IPv4 عمومی باشد).")
                return
            try:
                set_ip(uid, ip)
            except RuntimeError as e:
                send(cid, f"❌ خطا در اعمال: {e}")
                return
            send(cid, f"✅ ثبت شد: {ip}\n(چند ثانیه بعد فعال است)")
            return

        if cmd in ("/start", "/help"):
            send(cid, help_text(uid), keyboard(uid))
        elif cmd == "/link":
            send(
                cid,
                "🔗 لینک شخصی تو:\n"
                f"http://{SERVER_IP}:{LINK_PORT}/u/{me['token']}\n\n"
                "با گوشی یا کامپیوتری که به اینترنت همان خانه‌ی ایکس‌باکس وصل است و VPN خاموش است "
                "این لینک را باز کن؛ IP همان‌جا ثبت می‌شود.\n"
                "⚠️ لینک شخصی است، به کسی نده. اگر لو رفت: /newlink",
            )
        elif cmd == "/newlink":
            me["token"] = secrets.token_urlsafe(24)
            save()
            send(cid, "لینک قبلی باطل شد. /link را بزن تا لینک جدید را ببینی.")
        elif cmd == "/myip":
            send(cid, my_ips_text(uid))
        elif not admin:
            send(cid, "متوجه نشدم. /help", keyboard(uid))
        elif cmd == "/users":
            lines = []
            for i, u in STATE["users"].items():
                ips = ", ".join(f"{e['ip']} ({ago(e['ts'])})" for e in u["ips"]) or "بدون IP"
                lines.append(f"{ROLE_ICON.get(u['role'], '')} {u['name']} [{i}] — {u['role']}\n   {ips}")
            send(cid, "\n".join(lines))
        elif cmd == "/invite":
            want_admin = arg.lower() == "admin"
            if want_admin and not owner:
                send(cid, "فقط مالک می‌تواند ادمین دعوت کند.")
                return
            code = secrets.token_urlsafe(6)
            STATE["invites"][code] = {
                "role": "admin" if want_admin else "user",
                "expires": time.time() + INVITE_TTL,
                "by": uid,
            }
            save()
            send(
                cid,
                f"لینک دعوت ({'ادمین' if want_admin else 'کاربر'}) — یک‌بار مصرف، ۲۴ ساعت اعتبار:\n"
                f"https://t.me/{BOT_USERNAME}?start={code}",
            )
        elif cmd == "/remove":
            t = target_id(arg)
            if not t:
                send(cid, "استفاده: /remove ID  (ID را از /users ببین)")
            elif t == uid:
                send(cid, "خودت را نمی‌شود حذف کرد.")
            elif role(t) == "owner" or (role(t) == "admin" and not owner):
                send(cid, "اجازه‌ی حذف این کاربر را نداری.")
            else:
                gone = STATE["users"].pop(t)
                save()
                try:
                    apply_ips()
                except RuntimeError as e:
                    send(cid, f"❌ خطا در اعمال: {e}")
                send(cid, f"حذف شد: {gone['name']}")
                send(int(t), "دسترسی‌ات به ربات برداشته شد.")
        elif cmd == "/setip":
            parts = arg.split()
            t = target_id(arg)
            ip = parse_ip(parts[1]) if len(parts) > 1 else None
            if not t or not ip:
                send(cid, "استفاده: /setip ID IP")
            else:
                try:
                    set_ip(t, ip)
                    send(cid, f"✅ برای {STATE['users'][t]['name']} ثبت شد: {ip}")
                except RuntimeError as e:
                    send(cid, f"❌ خطا در اعمال: {e}")
        elif cmd == "/delip":
            ip = parse_ip(arg)
            if not ip:
                send(cid, "استفاده: /delip IP")
            else:
                for u in STATE["users"].values():
                    u["ips"] = [e for e in u["ips"] if e["ip"] != ip]
                save()
                try:
                    apply_ips()
                    send(cid, f"حذف شد: {ip}")
                except RuntimeError as e:
                    send(cid, f"❌ خطا در اعمال: {e}")
        elif cmd in ("/promote", "/demote"):
            t = target_id(arg)
            if not owner:
                send(cid, "فقط مالک.")
            elif not t or role(t) == "owner":
                send(cid, f"استفاده: {cmd} ID")
            else:
                STATE["users"][t]["role"] = "admin" if cmd == "/promote" else "user"
                save()
                send(cid, f"انجام شد: {STATE['users'][t]['name']} → {STATE['users'][t]['role']}")
                send(int(t), f"نقش تو شد: {STATE['users'][t]['role']} — /help", keyboard(t))
        elif cmd == "/status":
            send(cid, cli("status")[0])
        elif cmd == "/domains":
            send(cid, cli("list")[0])
        elif cmd in ("/adddomain", "/removedomain"):
            if not arg:
                send(cid, f"استفاده: {cmd} example.com")
            else:
                send(cid, cli("add" if cmd == "/adddomain" else "remove", arg.split()[0])[0])
        elif cmd == "/logs":
            send(cid, cli("logs")[0])
        else:
            send(cid, "متوجه نشدم. /help", keyboard(uid))


# ---------------------------------------------------------------- link endpoint
HITS = {}

PAGE = """<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>ثبت IP</title>
<style>body{font-family:sans-serif;text-align:center;padding:40px 16px}
button{font-size:20px;padding:14px 28px;border-radius:10px;border:0;background:#2a7;color:#fff}</style>
</head><body onload="document.f.submit()"><h2>ثبت IP</h2>
<p>IP فعلی شما: <b dir="ltr">__IP__</b></p>
<form name="f" method="post"><button type="submit">ثبت این IP</button></form></body></html>"""

DONE = """<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>انجام شد</title></head>
<body style="font-family:sans-serif;text-align:center;padding:40px 16px">
<h2>✅ IP ثبت شد</h2><p dir="ltr"><b>__IP__</b></p><p>چند ثانیه بعد فعال می‌شود. می‌توانی این صفحه را ببندی.</p></body></html>"""


def limited(ip):
    now = time.time()
    if len(HITS) > 1000:
        HITS.clear()
    hits = [t for t in HITS.get(ip, []) if now - t < 60]
    hits.append(now)
    HITS[ip] = hits
    return len(hits) > 20


class Handler(BaseHTTPRequestHandler):
    server_version = "x"
    sys_version = ""
    timeout = 10

    def log_message(self, *a):  # never log URLs (they contain tokens)
        pass

    def _reply(self, code, body):
        b = body.encode()
        self.send_response(code)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(b)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Robots-Tag", "noindex")
        self.end_headers()
        self.wfile.write(b)

    def _uid(self):
        m = re.fullmatch(r"/u/([A-Za-z0-9_-]{20,64})", self.path.split("?")[0])
        if not m:
            return None
        with LOCK:
            for uid, u in STATE["users"].items():
                if eq(u["token"], m.group(1)):
                    return uid
        return None

    def do_GET(self):
        if limited(self.client_address[0]):
            return self._reply(429, "Too many requests")
        if self._uid() is None:
            return self._reply(404, "Not found")
        self._reply(200, PAGE.replace("__IP__", self.client_address[0]))

    def do_POST(self):
        ip = self.client_address[0]
        if limited(ip):
            return self._reply(429, "Too many requests")
        try:
            self.rfile.read(min(int(self.headers.get("Content-Length") or 0), 1024))
        except Exception:  # noqa: BLE001
            pass
        uid = self._uid()
        if uid is None:
            return self._reply(404, "Not found")
        clean = parse_ip(ip)
        if not clean:
            return self._reply(400, "IP نامعتبر")
        try:
            set_ip(uid, clean)
        except RuntimeError as e:
            log("apply failed:", e)
            return self._reply(500, "Error")
        self._reply(200, DONE.replace("__IP__", clean))
        send(int(uid), f"✅ IP جدید از طریق لینک ثبت شد: {clean}")


# ---------------------------------------------------------------- main
def poll():
    offset = 0
    while True:
        try:
            res = tg("getUpdates", offset=offset, timeout=50, allowed_updates=["message"])
            for upd in res.get("result", []):
                offset = upd["update_id"] + 1
                m = upd.get("message")
                if m:
                    try:
                        handle(m)
                    except Exception as e:  # noqa: BLE001
                        log("handler error:", repr(e))
        except urllib.error.HTTPError as e:
            if e.code == 401:
                log("Invalid bot token")
                sys.exit(1)
            log("poll http error:", e.code)
            time.sleep(5)
        except Exception as e:  # noqa: BLE001
            log("poll error:", repr(e))
            time.sleep(5)


def main():
    global BOT_USERNAME
    try:
        tg("deleteWebhook")
    except Exception as e:  # noqa: BLE001
        log("deleteWebhook:", repr(e))
    BOT_USERNAME = tg("getMe")["result"]["username"]
    try:
        with LOCK:
            if all_ips():
                apply_ips()  # sync firewall with saved users
    except Exception as e:  # noqa: BLE001
        log("initial apply failed:", repr(e))
    srv = ThreadingHTTPServer(("0.0.0.0", LINK_PORT), Handler)
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    log(f"bot @{BOT_USERNAME} running; link endpoint on port {LINK_PORT}")
    poll()


if __name__ == "__main__":
    main()
BOT_PY_PAYLOAD_EOF

python3 -m py_compile "$T/bot.py"
bash -n "$T/smartdns.sh"

# ---- 3. Smart DNS (stops safely if ports are taken, e.g. by Amnezia) ----
if [ ! -f /etc/smartdns/state.env ]; then
  bash "$T/smartdns.sh" install
else
  install -m 755 "$T/smartdns.sh" /usr/local/bin/smartdns
  echo "Smart DNS already installed - updated the 'smartdns' command."
fi
# shellcheck disable=SC1091
. /etc/smartdns/state.env

# ---- 4. Bot ----
if [ -f /etc/smartdns/bot.json ]; then
  PORT=$(python3 -c 'import json;print(json.load(open("/etc/smartdns/bot.json"))["link_port"])')
else
  PORT=""
  for p in 8787 8788 8789 18787 28787; do
    if [ -z "$(ss -H -lnt "sport = :$p" 2>/dev/null)" ]; then PORT=$p; break; fi
  done
  [ -n "$PORT" ] || { echo "No free port found for the bot's link page."; exit 1; }
fi

mkdir -p /etc/smartdns /opt/smartdns-bot
BOT_TOKEN="$BOT_TOKEN" SERVER_IP="$PUBLIC_IP" LINK_PORT="$PORT" python3 - <<'PY'
import json, os
p = "/etc/smartdns/bot.json"
json.dump({"token": os.environ["BOT_TOKEN"], "server_ip": os.environ["SERVER_IP"],
           "link_port": int(os.environ["LINK_PORT"])}, open(p, "w"))
os.chmod(p, 0o600)
PY

if [ ! -f /etc/smartdns/users.json ]; then
  CLAIM=$(python3 -c 'import secrets;print(secrets.token_hex(6))')
  printf '{"owner_claim":"%s","users":{},"invites":{}}\n' "$CLAIM" > /etc/smartdns/users.json
  chmod 600 /etc/smartdns/users.json
fi
CLAIM=$(python3 -c 'import json;print(json.load(open("/etc/smartdns/users.json")).get("owner_claim") or "")')

install -m 755 "$T/bot.py" /opt/smartdns-bot/bot.py
cat > /etc/systemd/system/smartdns-bot.service <<'UNIT'
[Unit]
Description=Smart DNS Telegram manager bot
After=network-online.target smartdns-firewall.service
Wants=network-online.target

[Service]
Environment=PYTHONUNBUFFERED=1
ExecStart=/usr/bin/python3 /opt/smartdns-bot/bot.py
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT
systemctl daemon-reload
systemctl enable smartdns-bot >/dev/null 2>&1
systemctl restart smartdns-bot
sleep 3
systemctl is-active --quiet smartdns-bot || { echo "Bot failed to start. See: journalctl -u smartdns-bot -n 30"; exit 1; }

echo
echo "=============================================="
echo " All done."
echo "  Xbox DNS (manual):   $PUBLIC_IP"
echo "  Link page port:      $PORT/tcp  (open it in your provider's firewall if it has one)"
echo
if [ -n "$CLAIM" ]; then
  echo " LAST STEP - make yourself the owner of the bot by opening this link on your phone:"
  echo "   https://t.me/$BOT_USER?start=$CLAIM"
else
  echo " Bot: https://t.me/$BOT_USER  (owner already set)"
fi
echo " Then invite your friend from the bot with the 'Invite' button."
echo "=============================================="
